spring.application.name=resume-autofill


# Server
server.port=8080

# Multipart file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Affinda API
affinda.api.key=YOUR_AFFINDA_API_KEY_HERE
affinda.api.url=https://api.affinda.com/v2/resumes

