spring.application.name=resume-autofill


# Server
server.port=8080

# Multipart file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Affinda API
affinda.api.key=${AFFINDA_API_KEY}
affinda.api.url=https://api.affinda.com/v2/resumes

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
